name: Tabin CI/CD

on:
    push:
        branches: [dev]

jobs:
    slack_message:
        runs-on: ubuntu-latest
        steps:
            - name: Post to a Slack channel
              id: slack
              uses: slackapi/slack-github-action@v1.14.0
              with:
                  channel-id: "C02B03R0J05" # Slack channel id to post message
                  slack-message: "Electron build started!"
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    windows:
        runs-on: windows-latest
        env:
            CI: false #Need this otherwise github actions will do this => "Treating warnings as errors because process.env.CI = true"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: install node tools
              run: npm install --global --production windows-build-tools@4.0.0
            - name: install node-gyp
              run: npm install --global node-gyp@latest
            - name: Install dependencies
              run: npm install
            - name: Build native dependencies
              run: ./node_modules/.bin/electron-rebuild
            - name: Rebuild node-sass
              run: npm rebuild node-sass
            - name: Build web
              run: npm run build:web
            - name: Build desktop
              run: npm run build:desktop
            - name: Build/release Electron app
              uses: samuelmeuli/action-electron-builder@v1
              with:
                  # GitHub token, automatically provided to the action
                  # (No need to define this secret in the repo settings)
                  github_token: ${{ secrets.github_token }}

                  # If the commit is tagged with a version (e.g. "v1.0.0"),
                  # release the app after building
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}
                  args: "-w"
    macos:
        runs-on: macos-latest
        env:
            CI: false #Need this otherwise github actions will do this => "Treating warnings as errors because process.env.CI = true"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: Install dependencies
              run: npm install
            - name: Build native dependencies
              run: ./node_modules/.bin/electron-rebuild
            - name: Build web
              run: npm run build:web
            - name: Build desktop
              run: npm run build:desktop
            - name: Build/release Electron app
              uses: samuelmeuli/action-electron-builder@v1
              with:
                  # GitHub token, automatically provided to the action
                  # (No need to define this secret in the repo settings)
                  github_token: ${{ secrets.github_token }}

                  # If the commit is tagged with a version (e.g. "v1.0.0"),
                  # release the app after building
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}
                  args: "-m"
