name: Tabin CI/CD

on:
    push:
        branches: [dev]

jobs:
    windows:
        runs-on: windows-latest
        steps:
            # - name: Slack Notification
            #   uses: rtCamp/action-slack-notify@v2
            #   env:
            #       SLACK_CHANNEL: general
            #       SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
            #       SLACK_ICON: https://github.com/rtCamp.png?size=48
            #       SLACK_MESSAGE: "Post Content :rocket:"
            #       SLACK_TITLE: Post Title
            #       SLACK_USERNAME: rtCamp
            #       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: install node tools
              run: npm install --global --production windows-build-tools@4.0.0
            - name: install node-gyp
              run: npm install --global node-gyp@latest
            - name: Install dependencies
              run: npm install
            - name: Build native dependencies
              run: ./node_modules/.bin/electron-rebuild
            - name: Remove
              run: rm -r node_modules
            - name: Remove again
              run: rm -r package-lock.json
            - name: Install again
              run: npm install
            - name: Build web
              run: npm run build:web
            - name: Build desktop
              run: npm run build:desktop
            - name: Build/release Electron app
              run: GH_TOKEN=${{ secrets.GH_TOKEN }} npm run release:windows
